<?php
$atasozler=array(" Aba vakti aba, yaba vakti yaba alan yanılmaz.",
" Abanın kadri, yağmurda bilinir.",
" Abdal abdalın ne umduğunu, ne bulduğunu ister.",
" Abdal ata binmiş bey oldum sanmış.",
" Abdal düğünden, çocuk oyundan usanmaz.",
" Abdala kar yağıyor demişler, titremeye hazırım demiş.",
" Abdalın arkadaşlığı yol görününceye kadardır.",
" Abdalın karnı doyunca gözü pabucundadır.",
" Abdestsiz sofuya namaz dayanmaz.",
" Acele giden ecele gider.",
" Acele işe, şeytan karışır.",
" Acele yürüyen yolda kalır.",
" Acemi katır kapı önünde yük indirir.",
" Acemi marangozun talaşı tahtasından çok olur.",
" Acemi nalbant gibi kâh nalına vurur, kâh mıhına.",
" Acı acıyı bastırır, su sancıyı.",
" Acı patlıcanı kırağı çalmaz.",
" Acı söz insanı dininden çıkarır, tatlı söz yılanı deliğinden çıkarır.",
" Acıkan doymam, susayan kanmam sanır.",
" Acıkan yanağından, susayan dudağından belli olur.",
" Acındırırsan arsız, acıktırırsan hırsız olur.",
" Aç ayı oynamaz.",
" Aç aman bilmez, çocuk zaman bilmez.",
" Aç bırakma hırsız edersin, çok söyleme arsız edersin.",
" Aç doymam, tok acıkmam sanır.",
" Aç koyma hırsız olur, çok söyleme yüzsüz olur, çok değme arsız olur.",
" Aç koynunda azık durmaz.",
" Aç köpek fırın deler.",
" Aç kurt arslana saldırır.",
" Aç tavuk rüyasında kendini buğday ambarında görür.",
" Aç tokun halinden anlamaz.",
" Aça dokuz yorgan örtmüşler, yine uyuyamamış.",
" Açık yaraya kurt düşmez.",
" Açık ağız aç kalmaz.",
" Açık yerde tepecik kendini dağ sanır.",
" Açılan solar, ağlayan güler.",
" Açın imanı olmaz.",
" Açın karnı doyar gözü doymaz.",
" Açlık ile tokluğun arası bir dilim ekmek.",
" Açtırma kutuyu, söyletme kötüyü.",
" Adam adamdır olmasa da pulu, eşek eşektir olsa da çulu.",
" Adam eşeğinden, kadın döşeğinden belli olur.",
" Adam kıtlığında keçiye Abdurrahman Çelebi derler.",
" Adam olana bir söz yeter.",
" Adam sandık eşeği, altına serdik döşeği.",
" Adam yenilmekle marifetli olur, yanılmakla âlim.",
" Adamak kolay, ödemek güçtür.",
" Adamakla mal tükenmez.",
" Adamın iyisi iş başında belli olur.",
" Adı çıkacağına canı çıksın.",
" Adı çıktı dokuza, inmez sekize.",
" Ağaç kökünden yıkılır.",
" Ağaç ne kadar meyve verirse, dalı o kadar yere eğilir.",
" Ağaç ne kadar uzarsa uzasın göğe değmez.",
" Ağaç ne kadar yüksek olsa da yaprakları yere düşer.",
" Ağaç ucuna yel değer, güzel kişiye söz değer.",
" Ağaç yaşken eğilir.",
" Ağaca balta vurmuşlar sapı bendendir demiş.",
" Ağaca beşikten mezara kadar muhtacız.",
" Ağaca çıkan keçinin dama çıkan oğlağı olur.",
" Ağaca çıkan keçinin dala bakan oğlağı olur.",
" Ağaca dayanma çürür, insana güvenme ölür.",
" Ağacı kurt, insanı dert bitirir.",
" Ağaçlı köyü su basmaz.",
" Ağaçsız memleket duvaksız geline benzer.",
" Ağaçtan maşa, aptaldan paşa olmaz.",
" Ağaran baş, ağlayan göz gizlenmez.",
" Ağır baş iyidir, yenlik olsa uçar.",
" Ağır git ki yol alasın.",
" Ağır kazan geç kaynar.",
" Ağır otur, batman götür.",
" Ağır taş batman döver.",
" Ağır taş yerinden oynamaz.",
" Ağız yemeyince yüz utanmaz.",
" Ağlama ölü için, ağla deli için.",
" Ağlamayan çocuğa meme vermezler.",
" Ağlarsa anam ağlar, gerisi yalan ağlar.",
" Ağlayak da gözden mi olak?",
" Ağlayanın malından gülene hayır gelmez.",
" Ağrısız baş mezarda olur.",
" Ağustos ayında beyni kaynayanın, zemheride Zahmarıda kazanı kaynar.",
" Ağustosta beynin kaynasın, kışın da tencere kaynasın.",
" Ağzı açık ayran delisi.",
" Ağzına bir zeytin verir, ardına tulum tutar.",
" Ağzından bal akıyor.",
" Ah alan unmaz, ah yerde kalmaz.",
" Ahmak misafir, ev sahibini ağırlar.",
" Ak akçe kara gün içindir.",
" Ak gün ağartır‚ kara gün karartır.",
" Ak ile kara dere kenarında belli olur.",
" Ak koyunun kara kuzusu da olur.",
" Ak köpeğe koyun diye sarılma.",
" Akan su yosun tutmaz.",
" Akan su, pis tutmaz.",
" Akçe bulsam, çıkı yok.",
" Akıl, akıldan üstündür.",
" Akıl para ile satılmaz.",
" Akıl yaşta değil baştadır.",
" Akıl yiğide sermayedir.",
" Akılı olmayana neylesin sakal, kayışı tarladan götürür çakal.",
" Akıllı düşünene kadar, deli oğlunu evermiş, torunu olmuş.",
" Akıllı olan katar katar yer, akılsız olan satar satar yer.",
" Akılsız başın cezasını ayaklar çeker.",
" Akılsız köpeği yol kocatır.",
" Akılsızın şaşkını beyaz giyer kış günü.",
" Akıntıya kürek çekme, kurak yere ekin ekme.",
" Akranıyla konuşmayanın sesi, semadan gelir.",
" Akşam gelen misafirin, yiyeceği bulgur sıkısı, yatacağı ahır sekisi.",
" Akşamın hayrından sabahın şerri iyidir.",
" Al elmaya taş atan çok olur.",
" Al malın iyisini çekme kaygısını.",
" Al yakışırken, el bakışırken.",
" Alacağın bir iğne, çeliğin okkasını orantıya vurursun.",
" Alçak tavuk kendini ferik gösterir.",
" Alışmış kudurmuştan beterdir.",
" Alim unutmuş, kalem unutmamış.",
" Allah aptala eşeğini kaybettirir, sonra buldurup sevindirirmiş.",
" Allah dağına göre kar verir.",
" Allah şaşırttı mı, dayıya hala dedirtirmiş.",
" Allı yelek, pullu yelek, canfes neye gerek?",
" Alma el kızının ahını, gökten indirir şahini.",
" Alma mazlumun ahını, çıkar aheste aheste.",
" Alma mazlumun ahını, gökden indirir şahını.",
" Almadan vermek Allaha mahsustur.",
" Almak kolay ödemek zordur.",
" Altın anahtar, her kapıyı açar.",
" Altın eşik, ağaç eşiğe muhtaçtır.",
" Altın kılıç demir kapıyı açar.",
" Altın yere düşmekle pul olmaz.",
" Altının değerini sarraf bilir.",
" Ana gibi yâr, Bağdat gibi diyar olmaz.",
" Anan gibi saç büyüteceğine, baban gibi bıyık büyüt.",
" Anan turp, baban şalgam, sen içinde gülbe şeker.",
" Ananın bastığı yavru incinmez.",
" Ananın bastığı yerde yavru ölmez.",
" Anasına bak kızını al, astarına bak bezini al.",
" Anasına bak kızını al, kenarına bak bezini al.",
" Anlayana sivrisinek saz, anlamayana davul zurna az.",
" Aptalın karnı doyunca gözü yolda olur.",
" Ar gözden, kâr yüzden anlaşılır.",
" Ar namus hak getire.",
" Arap eli öpmek, dudak karartmaz.",
" Arayan belasını da devasını da bulur.",
" Arayan bulur, inleyen ölür.",
" Arefe günü yalan söyleyenin, bayram günü yüzü kara çıkar.",
" Arı bal yapacak çiçeği bilir.",
" Arı kahrını çekmeyen balın kadrini ne bilir.",
" Arı satmış namusu tellala vermiş.",
" Arkadaş dediğinin gölgesinde suç işlenir.",
" Arkadaşını söyle ki, sana kim olduğunu söyleyeyim.",
" Arkalı it kurdu boğar.",
" Armudu sapıyla, üzümü çöpüyle, pekmezi küpüyle.",
" Arpa eken darı biçmez.",
" Arpa ekip buğday bekleme.",
" Asıl azmaz, bal kokmaz; kokarsa yağ kokar, onun da aslı ayrandır.",
" Aslan yattığı yerden belli olur.",
" Aslı neyse nesli odur.",
" Aslına çekmeyen haramzadedir.",
" Aslında olan tırnağına getirir.",
" Aslını inkâr eden haramzâdedir.",
" Aslını inkâr edenin nesli gevşek olur.",
" Aş kaşık ile, iş keşik ile.",
" Aş sabahın iş sabahın.",
" Aşağı tükürsen sakal, yukarı tükürsen bıyık.",
" Aşk olmayınca meşk olmaz.",
" At alırsan yazın, deve alırsan güzün, avrat alırsan gezin ha gezin.",
" At binenin kılıç kuşananındır.",
" At ile avrat yiğidin ikbalindendir.",
" At karnından yiğit burnundan bellidir.",
" At olacak tay yürüyüşünden belli olur.",
" At ölür itlere bayram olur.",
" At ölür meydan kalır, yiğit ölür şan kalır.",
" At ver hasım ol, kız ver hısım ol.",
" At yedi günde, it yediği günde unutur.",
" At, sahibine göre kişner.",
" Ata binmek bir ayıp, inmek iki ayıp.",
" Ata et, ite ot verilmez.",
" Ata sözü tutmayan, uluya uluya kalır.",
" Ateş düştüğü yeri yakar.",
" Ateş ile barut bir arada olmaz.",
" Ateş olmayan yerden duman çıkmaz.",
" Atı alan Üsküdarı geçti.",
" Atılan ok geri dönmez.",
" Atımın anlı sakar, lakabını ele takar.",
" Atın iyisi arkadan gelmez.",
" Atın iyisine doru, yiğidin iyisine deli derler.",
" Atın ölümü arpadan olsun.",
" Atlar tepişirken arada eşekler ezilir.",
" Atlı, itli sığmış, bir çocuk sığmamış.",
" Attan düşen kaba döşek, eşekten düşen kazma kürek.",
" Attan düşen ölmez, eşekten düşen ölür.",
" Attan indi eşeğe bindi.",
" Avradı er zapt etmez, ar zapt eder.",
" Avrat var ev yapar, avrat var ev yıkar.",
" Ay bozmaz, süt kokmaz.",
" Ayağa değmedik taş, başa gelmedik iş olmaz.",
" Ayağın sığmayacağı yere baş sokulmaz.",
" Ayağını yorganına göre uzat.",
" Aydan gelen halı üstüne, günde gelen kül üstüne.",
" Ayranım ekşidir diyen olmaz.",
" Az kazanan çok kazanır, çok kazanan hiç kazanır.",
" Az menfaat çok zarara mal olur.",
" Az sabırda, çok keramet vardır.",
" Az tamah, çok ziyan getirir.",
" Az veren candan, çok veren maldan verir.",
" Az yaşa, uz yaşa, akıbet gelecek başa.",
" Azan mevlasını da bulur, belasını da.",
" Azı bilmeyen çoğu hiç bilmez.",
" Azıcık aşım, kaygısız başım.",
" Azıksız yola çıkanın, iki gözü el torbasında olur.",
" Azmış, kudurmuştan beterdir.",
" Baba borç yapar çol çocuk aç yatar.",
" Baba ekmeği zindan ekmeği, koca ekmeği meydan ekmeği.",
" Baba koruk yer, oğlunun dişi kamaşır.",
" Baba mirası yanan mum gibidir.",
" Baba oğula bağ bağışlamış, oğul babaya bir salkım üzüm vermemiş.",
" Babadan mal kalır, kemal kalmaz.",
" Baban bana öğüt verirken, ben inek gözünde kırk sinek saydım.",
" Babası ölen bey, anası ölen kadın olur.",
" Babasına hayır etmeyenin kimseye hayrı olmaz.",
" Babaya dayanma, karıya güvenme.",
" Baca eğride olsa, dumanı doğru çıkar.",
" Bacak kadar boyu var, türlü türlü huyu var.",
" Bağ dua değil, çapa dua ister.",
" Bağa bak üzüm olsun, yemeye yüzün olsun.",
" Bağa gir izin olsun ki, yemeye yüzün ola.",
" Bağlı aslana tavşan bile hücum eder.",
" Bahar çiçeğiyle güzeldir.",
" Baht olmayınca başa, ne kuruda biter, nede yaşta.",
" Bakacağın yüze sıçma, sıçacağın yüze bakma.",
" Bakarsan bağ, bakmazsan dağ olur.",
" Bakkal ölenin borcunu, diriye ödettirir.",
" Bakmakla öğrenilseydi, kediler kasap olurdu.",
" Bal döksen yalanır.",
" Bal olan yerde sinek de bulunur.",
" Bal tutan parmağını yalar.",
" Bal yiyen baldan bıkar.",
" Bal, bal demekle ağız tatlanmaz.",
" Balı parmağı uzun olan değil, kısmeti olan yer.",
" Bana benden olur, her ne olursa, başım rahat bulur, dilim durursa.",
" Bana dokunmayan yılan bin yıl yaşasın.",
" Baskın basanındır.",
" Baskısız yongayı yel alır.",
" Bastığın yer bayram olsun.",
" Baş başa, baş da padişaha bağlıdır.",
" Baş nereye giderse, oyak oradadır.",
" Başıma uymayan takke elin olsun.",
" Başındaki fese bak, girdiği kümese bak.",
" Başını ecemi berbere teslim eden, cebinde pamuk eksik etmesin.",
" Başsız evin köpeği çok havlar.",
" Bazen inek, erkek; bazen de dişi doğurur.",
" Bebeler birbirinden huy kapar, ayranlarına su katar.",
" Bedava sirke baldan tatlıdır.",
" Bekâr gözü ile kız alınmaz.",
" Bekâr gözü kör gözü.",
" Bekâra karı boşamak kolay gelir.",
" Bekârlık maskaralıktır.",
" Bekarın ahmağı akşam, evlinin ahmağı sabah traş olur.",
" Bekârın parasını it yer, yakasını bit.",
" Bekleyen derviş muradına ermiş.",
" Beleş peynir fare kapanında bulunur.",
" Belli düşman, gizli dosttan yeğdir.",
" Benden sana öğüt, ununu elinle öğüt.",
" Benim adım Hıdır, elimden gelen budur.",
" Benim sakalım tutuştu, sen cigara yakmak istersin.",
" Besle kargayı oysun gözünü.",
" Besledik büyüttük danayı, şimdi tanımaz oldu anayı, babayı.",
" Beş kuruşluk fener o kadar yanar.",
" Beş parmağın beşi de bir değil.",
" Beyaz saç, aklın değil yaşın işaretidir.",
" Bıçak sapını kesmez.",
" Bıçak yarası geçer, dil yarası geçmez.",
" Bıldır ki hurmalar götünü tırmalar.",
" Bilgisiz insan meyvesiz ağaca benzer.",
" Bilinmedik aş, ya karın ağrıtır ya baş.",
" Bilmediği beş vakit namaz, bilirde yanına varmaz.",
" Bilmediklerimi ayağımın altına koysam, başım göğe değer.",
" Bilmemek ayıp değil öğrenmemek ayıptır.",
" Bin atın varsa bin dinlen, bir atın varsa in dinlen.",
" Bin bilsen de bir bilene danış.",
" Bin dinle, bir söyle.",
" Bin ölçüp bir biçmeli.",
" Binde bir gelinen yere gül döşerler, her gün gelinen yere kül döşerler.",
" Bir adamın adı çıkacağına, canı çıksın.",
" Bir adamın karısı onun yarısıdır.",
" Bir ağaçta gül de biter, diken de.",
" Bir ağaçtan, oklukta çıkar boklukta.",
" Bir ağızdan çıkan, bin ağza yayılır.",
" Bir ahırda at da bulunur eşek de.",
" Bir ayağı çukurda.", 
" Bir bulutla kış gelmez.",
" Bir bütün bir yarımdan iyidir.",
" Bir dalın gölgesinde bin koyun eğlenir.",
" Bir dirhem et, bin ayıp örter.",
" Bir elin nesi var, iki elin sesi var.",
" Bir elin verdiğini, öbür elin duymasın.",
" Bir eve bir baca, bir kadına bir koca.",
" Bir fincan kahvenin kırk yıl hatırı vardır.",
" Bir işe başlamak, bitirmenin yarısıdır.",
" Bir koyun başı pişinceye kadar, kırk kuzu başı pişer.",
" Bir koyundan iki post olmaz.",
" Bir musibet bin nasihatten iyidir.",
" Bir nalına vurur, bir mıhına.",
" Bir yerim diyenden birde yemem diyenden kork.",
" Bir yiğit kırk yılda meydana gelir.",
" Biri eşikte, biri beşikte.",
" Biri yer, biri bakar, kıyamet ondan kopar.",
" Birlikten kuvet doğar.",
" Bitli baklanın kör alıcısı olur.",
" Bize gelince yiyip içelim, size gelince gülüp geçelim.",
" Boğulursan büyük suda -denizde- boğul.",
" Borcun iyisi vermek, derdin iyisi ölmektir.",
" Borç yiğidin kamçısıdır.",
" Boş duranı Allah da sevmez kuluda.",
" Boş fıçı çok langırdar.",
" Boşboğazı cehenneme atmışlar, ‘odun yaş’ diye bağırmış.",
" Boşboğazın sigarası yanmaz.",
" Bu dünya iki kapılı handır, gelen bilmez giden bilmez.",
" Bugünün küçükleri yarının büyükleri.",
" Budalanın yağı çok olursa sakalına sürer.",
" Bugün bana ise yarın sana.",
" Bugünkü işini yarına bırakma.",
" Bugünkü tavuk, yârınki kazdan iyidir.",
" Bülbülü altın kafese koymuşlar ah vatanım demiş.",
" Bülbülün çektiği; dili belasıdır.",
" Büyük ekmek, büyük bezeden olur.",
" Büyük lokma çukurda kalır.",
" Büyük lokma ye, büyük söz söyleme.",
" Büyük zekâlar birlikte düşünürler.",

" Cahil adam meyve vermeyen ağaca benzer.",
" Cahile söz anlatmaktansa, deveye hendek atlatmak iyidir.",
" Cahilin dostluğundan alimin düşmanlığı yeğdir.",
" Cahille arkadaş olma küstürün, cam kırığıyla kıçını silme kestirirsin.",
" Cami ne kadar büyük olsa imam bildiğini okur.",
" Caminin kapısını bilmez, sofuluk taslar.",
" Can boğazdan gelir.",
" Can cümleden azizdir.",
" Can çıkar, huy çıkmaz.",
" Can çıkmadan ümit kesilmez.",
" Cana gelecek mala gelsin.",
" Canı kaymak isteyen mandayı yanında taşır.",
" Canı yanan eşek atı geçer.",
" Cefayı çekmeyen sefanın kadrini bilemez.",
" Cins kedi ölüsünü göstermez.",
" Cömert derler, maldan ederler, yiğit derler candan ederler.",
" Cömert ile nekesin harcı birdir.");
$say=count($atasozler);
$sec=rand(0,$say-1);
echo "Toplam $say adet atasözü var. $sec. atasözü : $atasozler[$sec]";




echo"<br>","<br>";


//for ($x=0;$x<$say;$x++){
//    echo$atasozler[$x];
//   echo "<br>";}



?>